# adding patrons for making possible statments users will write to chatbot 

In [2]:
categories = ['short','long','old','recent','local','foregin','action',
       'anime', 'classic', 'comedy', 'documental', 'drama', 'family',
       'fantasy', 'lgbt', 'music', 'religion', 'romance', 'show',
       'sports', 'suspense']

In [3]:
len(categories)

21

from movies categories we have categories = ['short','long','old','recent','local','foregin','action',
       'anime', 'classic', 'comedy', 'documental', 'drama', 'family',
       'fantasy', 'foregin', 'lgbt', 'music', 'religion', 'romance', 'show',
       'sports', 'suspense']

In [4]:
say_hello = ['hi','hey!','hello','nice to meet you','how your doing','how is it going']

In [5]:
modals = ['could you','would you','can you','will you','would you mind to']

In [6]:
request = ['i need','i want','id like','i wanna','im in the mood for','im lookin for']

In [7]:
make_request = ['recommend me','please make me a recommendation for','give me','pass me','gimme']

In [8]:
auxiliars = ['something','some','any','anything']

keywords for categories classification 

In [9]:
categories[6:]

['action',
 'anime',
 'classic',
 'comedy',
 'documental',
 'drama',
 'family',
 'fantasy',
 'lgbt',
 'music',
 'religion',
 'romance',
 'show',
 'sports',
 'suspense']

In [10]:
categories_keywords = {
    'short': ["Quick", "Brief", "not long", "Concise", "Compact", "Summarized", "Pithy", "Short-form", "Swift", "short"],
    'long': ["Extended", "Lengthy", "Comprehensive", "long", "In-depth", "Detailed", "Expansive", "Extensive", "Prolonged", "Lengthened"],
    'old': ["Vintage", "Classic", "Retro", "Antique", "Historic", "Timeless", "Iconic", "old", "Golden-age", "Aged"],
    'recent': ["Recent", "New", "Modern", "Contemporary", "Fresh", "Latest", "Current", "Up-to-date", "Newly-released", "Recent-release"],
    'local': ["Local", "Regional", "Native", "Community", "Domestic", "Hometown", "Provincial", "Homegrown", "Neighborhood", "Indigenous"],
    'foregin': ["Foreign", "International", "Global", "Overseas", "Exotic", "Imported", "Non-native", "Alien", "Extraterritorial", "Exogenous"],
    'action': ["Action", "Thrilling", "Adrenaline", "Exciting", "Intense", "Fast-paced", "Gritty", "Explosive", "Stunt-filled", "Dynamic"],
    'anime': ["Anime", "Animated", "Cartoon", "Animation", "Manga", "Japanese", "Animated-series", "Otaku", "Anime-film", "Anime-series"],
    'classic': ["Classic", "Vintage", "Iconic", "Timeless", "Golden-age", "Historic", "Legendary", "Old-school", "Traditional", "Cinematic"],
    'comedy': ["Comedy", "Funny", "Humorous", "Hilarious", "Light-hearted", "Witty", "Satirical", "Laugh-out-loud", "Amusing", "Entertaining"],
    'documental': ["Documentary", "Factual", "Informative", "Educational", "realistic", "True-story", "Real-life", "Expository", "Investigative", "Historical"],
    'drama': ["Drama", "Emotional", "Intense", "Gripping", "Heart-wrenching", "Serious", "Poignant", "Compelling", "Powerful", "Moving"],
    'family': ["Family", "Kid-friendly", "Children", "Wholesome", "All-ages", "Parental", "Feel-good", "Heartwarming", "Adventurous", "Animated"],
    'fantasy': ["Fantasy", "Magical", "Whimsical", "Enchanting", "Epic", "Mythical", "Imaginary", "Fairy-tale", "Otherworldly", "Supernatural"],
    'lgbt': ["LGBT", "Queer", "Gay", "Lesbian", "Transgender", "Inclusive", "Diverse", "Pride", "Rainbow", "Equality"],
    'music': ["Music", "Musical", "Melodious", "Rhythmic", "Tuneful", "Harmonious", "Singing", "Instrumental", "Concert", "Rock"],
    'religion': ["Religion", "Spiritual", "Faith-based", "Sacred", "Divine", "Inspirational", "Theological", "Devotional", "Cultural", "Ritual"],
    'romance': ["Romance", "Love", "Love-story", "Heartfelt", "Passionate", "Affectionate", "Sentimental", "Intimate", "Tender", "Charming"],
    'show': ["Show", "Series", "TV", "Television", "Binge-worthy", "Episodic", "Serial", "Entertainment", "Program", "Stream"],
    'sports': ["Sports", "Athletic", "Sporting", "Competitive", "Physical", "Games", "Team", "Athlete", "Olympics", "Fitness"],
    'suspense': ["Suspense", "Thriller", "Mystery", "Tense", "Nail-biting", "Intriguing", "Edge-of-your-seat", "Puzzling", "Gripping", "Taut"]
}

We build statments for each category :


In [11]:
import pandas as pd
def make_statments(categories:list,number_stats:int,keywords:dict,random_state):
    import random
    random.seed(42)
    statments = pd.DataFrame()
    df_final = pd.DataFrame()
   
    for category in categories:
        stat_list = []
        target_list = []
        for i in range(0,number_stats):
            statm = str(random.choice(say_hello)+' '+random.choice(request)+' '+random.choice(auxiliars)+' ' +random.choice(keywords[category]))
            stat_list.append(statm)
            target_list.append(category)
        statments['text'] = stat_list
        statments['target'] = target_list
        df_final= pd.concat([df_final,statments],ignore_index=True)
    return df_final


In [12]:
df = make_statments(categories=categories,number_stats=100,keywords=categories_keywords,random_state=42)
df

text    target
0            how is it going i need something Compact     short
1                              hey! i want some Brief     short
2       how is it going im lookin for something short     short
3             nice to meet you i need something Brief     short
4                         hey! i want something Swift     short
...                                               ...       ...
2095                 nice to meet you i want any Taut  suspense
2096  how is it going im lookin for anything Thriller  suspense
2097                       hi i wanna some Intriguing  suspense
2098   how is it going i wanna some Edge-of-your-seat  suspense
2099             how is it going i wanna any Thriller  suspense

[2100 rows x 2 columns]

# Machine learning modelo for multinomial logistic regression 


In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
cv = CountVectorizer(max_features=2200,lowercase=True)

In [15]:
matrix = cv.fit_transform(df['text']).toarray()

In [16]:
cv.get_feature_names_out()

array(['action', 'adrenaline', 'adventurous', 'affectionate', 'age',
       'aged', 'ages', 'alien', 'all', 'amusing', 'animated', 'animation',
       'anime', 'antique', 'any', 'anything', 'athlete', 'athletic',
       'based', 'binge', 'biting', 'brief', 'cartoon', 'charming',
       'children', 'cinematic', 'classic', 'comedy', 'community',
       'compact', 'compelling', 'competitive', 'comprehensive', 'concert',
       'concise', 'contemporary', 'cultural', 'current', 'date', 'depth',
       'detailed', 'devotional', 'diverse', 'divine', 'documentary',
       'doing', 'domestic', 'drama', 'dynamic', 'edge', 'educational',
       'emotional', 'enchanting', 'entertaining', 'entertainment', 'epic',
       'episodic', 'equality', 'exciting', 'exogenous', 'exotic',
       'expansive', 'explosive', 'expository', 'extended', 'extensive',
       'extraterritorial', 'factual', 'fairy', 'faith', 'family',
       'fantasy', 'fast', 'feel', 'filled', 'film', 'fitness', 'for',
       'foreign'

In [17]:
import pickle
pickle.dump(cv,open('../english_version/objects/vectorizer.pkl','wb'))

In [18]:
from sklearn .model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [19]:
encoder = LabelEncoder()

In [20]:
y = df['target'].values
x = matrix

In [21]:
x[0], y[0]

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0]),
 'short')

In [22]:
y_encoder = encoder.fit_transform(y)

In [23]:
x[0], y[0]

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0]),
 'short')

In [24]:
y.shape, x.shape

((2100,), (2100, 246))

In [25]:
set(y)

{'action',
 'anime',
 'classic',
 'comedy',
 'documental',
 'drama',
 'family',
 'fantasy',
 'foregin',
 'lgbt',
 'local',
 'long',
 'music',
 'old',
 'recent',
 'religion',
 'romance',
 'short',
 'show',
 'sports',
 'suspense'}

In [26]:
pd.DataFrame({'target':y}).value_counts()

target    
action        100
long          100
sports        100
show          100
short         100
romance       100
religion      100
recent        100
old           100
music         100
local         100
anime         100
lgbt          100
foregin       100
fantasy       100
family        100
drama         100
documental    100
comedy        100
classic       100
suspense      100
Name: count, dtype: int64

In [27]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(multi_class='multinomial',solver='saga',penalty='l2',)

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x, y_encoder, test_size=0.25, random_state=42, shuffle=True)

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [30]:
log_reg.fit(x_train,y_train)
pred = log_reg.predict(x_test)
print(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))

/home/ackerman/anaconda3/envs/chatbot_nltk/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


0.9561904761904761
[[23  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 19  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 17  0  0  0  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0]
 [ 0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2]
 [ 0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 32  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 33  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 31  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 31  0  0  0  0  0  0  0  0]
 [ 0  0 13  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 30  0  0  0  

#accuracy de 96% not that bad but, lets prove this model with data generated...

In [31]:
import pandas as pd
def make_statments(categories:list,number_stats:int,keywords:dict,random_state:int):
    import random
    random.seed(random_state)
    statments = pd.DataFrame()
    df_final = pd.DataFrame()
   
    for category in categories:
        stat_list = []
        target_list = []
        for i in range(0,number_stats):
            statm = str(random.choice(say_hello)+' '+random.choice(modals)+' '+random.choice(make_request)+' '+random.choice(auxiliars)+' ' +random.choice(keywords[category]))
            stat_list.append(statm)
            target_list.append(category)
        statments['text'] = stat_list
        statments['target'] = target_list
        df_final= pd.concat([df_final,statments],ignore_index=True)
    return df_final

In [32]:
df_prueba = make_statments(categories=categories,number_stats=30,keywords=categories_keywords,random_state=0)
df_prueba

text    target
0     nice to meet you will you recommend me any Swift     short
1    nice to meet you will you give me anything Sum...     short
2          how your doing would you gimme some Compact     short
3                       hey! could you gimme any Swift     short
4    how is it going would you mind to please make ...     short
..                                                 ...       ...
625                  hello could you pass me any Tense  suspense
626  nice to meet you will you give me anything Mys...  suspense
627      how your doing will you give me some Suspense  suspense
628            hey! can you give me something Suspense  suspense
629   nice to meet you can you give me some Intriguing  suspense

[630 rows x 2 columns]

In [33]:
def get_predictions_test(cv,encpder_model,random_state,regresion_model):
    df_prueba = make_statments(categories=categories,number_stats=100,keywords=categories_keywords,random_state=random_state)
    x = cv.transform(df_prueba['text']).toarray()
    print(x)
    y = df_prueba['target'].values
    print(y.shape)
    y_encoded = encpder_model.transform(y)
    print(set(y_encoded))
    
    prediction = regresion_model.predict(x)
    print(prediction)
    print(accuracy_score(y_encoded,prediction))
    print(confusion_matrix(y_encoded,prediction))

    

In [34]:
get_predictions_test(cv=cv,encpder_model=encoder,random_state=0,regresion_model=log_reg)

[[0 0 0 ... 0 2 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 1 1]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 1]
 [0 0 0 ... 0 1 1]]
(2100,)
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}
[17 17 17 ...  5 20 20]
0.9533333333333334
[[ 90   0   0   0   0  10   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0  91   0   0   0   0   9   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0  82   0   0   0   0   0   0   0   0   0   0  18   0   0   0   0
    0   0   0]
 [  0   0   0 100   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0 100   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0  94   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   6]
 [  0   0   0   0   0   0 100   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0 100   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   0 100   0 

we got 96% accuracy for new data generated

In [35]:
import numpy as np
def prediction():    
    text = input('')
    text = text.lower()
    matrix = cv.transform([text]).toarray()
    matrix = np.squeeze(matrix)
    prediction = log_reg.predict(matrix.reshape(1,-1))
    print(log_reg.predict_proba(matrix.reshape(1,-1))*100)
    print(text,encoder.inverse_transform(prediction))



In [40]:
pickle.dump(encoder,open('../english_version/objects/encoder.pkl','wb'))

In [36]:
# while True:
#     prediction()

In [37]:
import joblib

In [38]:
joblib.dump(log_reg,'../english_version/models/english_model.joblib')

['../english_version/models/english_model.joblib']