In [33]:
say_hello =  [
    "Hello",
    "Good morning",
    "Good afternoon",
    "Good evening",
    "Hi, how are you?",
    "Hey there!",
    "Hey!",
    "Hi",
    "Greetings",
    "Good day",
    "Hello there!",
    "Hello, how's it going?",
    "Hey, what's up?",
    "Hey, friend!",
    "Hey, buddy!",
    "Hi there!",
    "Hi, good morning!",
    "Hi, good afternoon!",
    "Hi, good evening!",
    "Hi, how are you doing?",
    "Hi, it's good to see you!",
    "Hi, how have you been?",
    "Hi, nice to see you!",
    "Hi, hope you're well!",
    "Hi, hope everything's going well!",
    "Hi, how's everything?",
    "Hi, what's new?",
    "Hi, long time no see!",
    "Hi, what's happening?",
    "Hi, how's your day going?",
    "Hello, how are you?",
    "Good morning, how's your day going so far?",
    "Good afternoon, how are things with you?",
    "Good evening, how was your day?",
    "Hi, how are you doing today?",
    "Hey there, how have you been?",
    "Hey, what's new with you?",
    "Hi, how's everything going?",
    "Greetings, how's your day been?",
    "Good day, how's it going?",
    "Hello there, how are you feeling?",
    "Hello, how's everything with you?",
    "Hey, how are things going for you?",
    "Hey, friend, how have you been lately?",
    "Hey, buddy, how's life treating you?",
    "Hi there, how's your day been so far?",
    "Hi, good morning, how are you today?",
    "Hi, good afternoon, how's it going?",
    "Hi, good evening, how's your night going?",
    "Hi, how's your day shaping up?",
    "Hi, it's good to see you! How are you?",
    "Hi, how have you been keeping?",
    "Hi, nice to see you! How are things?",
    "Hi, hope you're well! How's everything?",
    "Hi, hope everything's going well! How are you?",
    "Hi, how's everything been going for you?",
    "Hi, what's new with you lately?",
    "Hi, long time no see! How have you been?",
    "Hi, what's happening with you?",
    "Hi, how's your day going? Anything exciting?"

]

In [34]:
ask_information = [
    "Could you tell me about",
    "I'd like to know",
    "Can you explain",
    "Do you have any information on",
    "Could you provide more details about",
    "What can you tell me about",
    "I'm interested in learning more about",
    "Would you mind telling me",
    "Could you clarify",
    "Can you give me an update on",
    "Do you happen to know",
    "I'm curious about",
    "I'd appreciate it if you could tell me",
    "Could you shed some light on",
    "I'm wondering if you could explain",
    "Would you be able to share",
    "Could you elaborate on",
    "Do you have any insight into",
    "I'd like to find out more about",
    "Can you shed some more information on",
    "Could you fill me in on",
    "I'm looking for information on",
    "Would it be possible to get some details on",
    "Do you know anything about",
    "I'd love to hear more about",
    "Can you provide some context on",
    "Would you mind giving me some background on",
    "Could you update me on",
    "Can you brief me on",
    'what is your function?',
    'i need help',
    'can un help me?',
    'gimme information please',
    'info',
    'what can you do for me',
    'give me info please',
    'gimme information',
    'tell me about you',
    'what can you do?',
    'explain yourself',
    'whats this?',
    'what is this?'
]


In [35]:
ask_recommendation = [
    "Could you recommend something to watch",
    "What would you recommend watching",
    "Do you have any recommendations on what to watch",
    "Can you suggest something good to watch",
    "Could you give me a recommendation for something to watch",
    "I'm looking for a good show/movie to watch, any recommendations",
    "Any suggestions on what to watch",
    "I'm in the mood for something new, any recommendations",
    "Could you suggest a movie/TV show to watch",
    "Do you know any good movies/TV shows to watch",
    "I'm trying to find something interesting to watch, any ideas",
    "I'm looking for recommendations on what to watch",
    "I'm looking for something to binge-watch, any recommendations",
    "Could you recommend a good series/movie to watch",
    "Do you have any suggestions for what I should watch",
    "Can you recommend something interesting to watch",
    "I'm looking for a recommendation on what to watch",
    "Could you suggest a good movie/TV show to watch",
    "Any good movies/series you could recommend",
    "What are your recommendations for something to watch",
    "Can you recommend a must-watch series/movie",
    "Any ideas on what I should watch",
    "I need recommendations for what to watch",
    "Could you suggest a show/movie to watch",
    "Any recommendations for shows/movies",
    "What should I watch next",
    "Looking for recommendations on what to watch",
    "Any recommendations on what's good to watch",
    "I'm looking for something entertaining to watch, any suggestions",
    "Any recommendations for a good series/movie",
    'i want to watch some',
    'i need to relax',
    'give me something to watch',
    'movie',
    'tv show',
    'take to your recommendation system',
    'take me to your recommendation function',
    'take me to recommendations',
    'take me to your movies section',
    'i wanna watch some',
    'gimme some to see',
    'gimme som to watch'
]

In [36]:
thank_you = [
    "Thank you",
    "Thanks",
    "Thank you so much",
    "Thanks a lot",
    "Thanks a bunch",
    "Thanks a million",
    "Thank you very much",
    "Thank you kindly",
    "Many thanks",
    "Much obliged",
    "I appreciate it",
    "I'm grateful",
    "I owe you one",
    "I can't thank you enough",
    "You're too kind",
    "I'm so thankful",
    "That's so thoughtful of you",
    "I'm indebted to you",
    "I'm grateful for your help",
    "Thanks for everything",
    "Thanks for your help",
    "Thanks a ton",
    "Thanks a heap",
    "Thanks a bunch",
    "I want to express my gratitude",
    "I want to thank you from the bottom of my heart",
    "I want to extend my appreciation",
    "You have my thanks",
    "I truly appreciate it",
    "I really appreciate your help"
]


In [37]:
len(set(say_hello)), len(ask_information), len(ask_recommendation), len(thank_you)

(60, 42, 42, 30)

In [38]:
data = say_hello + ask_information + ask_recommendation + thank_you

In [39]:
len(data)

174

In [40]:
def labels(hello_list,info_list,recomm_list,thanks_list):
  import numpy as np
  import pandas as pd
  text_list = list(set(hello_list)) + list(set(info_list)) + list(set(recomm_list))+ list(set(thanks_list))
  n_text = len(text_list)
  hello_range = len(set(hello_list))
  info_range = hello_range+len(set(info_list))
  recomm_range = info_range + len(set(recomm_list))
  thanks_range = recomm_range + len(set(thanks_list))
  df = pd.DataFrame({'text':data})
  df['labels'] = None
  df['labels'].iloc[0:hello_range] = 'hello_trigger'
  df['labels'].iloc[hello_range:info_range] = 'info_trigger'
  df['labels'].iloc[info_range:recomm_range] = 'recomm_trigger'
  df['labels'].iloc[recomm_range:thanks_range+1] = 'thanks_trigger'
  return df

In [41]:
labels(say_hello,ask_information,ask_recommendation,thank_you)['labels'].value_counts()

/tmp/ipykernel_26703/2111032620.py:12: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['labels'].iloc[0:hello_range] = 'hello_trigger'
/tmp/ipykernel_26703/2111032620.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pa

labels
hello_trigger     60
info_trigger      42
recomm_trigger    42
thanks_trigger    30
Name: count, dtype: int64

In [42]:
df = labels(say_hello,ask_information,ask_recommendation,thank_you)
df

/tmp/ipykernel_26703/2111032620.py:12: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['labels'].iloc[0:hello_range] = 'hello_trigger'
/tmp/ipykernel_26703/2111032620.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pa

text          labels
0                                              Hello   hello_trigger
1                                       Good morning   hello_trigger
2                                     Good afternoon   hello_trigger
3                                       Good evening   hello_trigger
4                                   Hi, how are you?   hello_trigger
..                                               ...             ...
169  I want to thank you from the bottom of my heart  thanks_trigger
170                 I want to extend my appreciation  thanks_trigger
171                               You have my thanks  thanks_trigger
172                            I truly appreciate it  thanks_trigger
173                    I really appreciate your help  thanks_trigger

[174 rows x 2 columns]

In [43]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(lowercase = True,stop_words=None)
bow = cv.fit_transform(data).toarray()

In [44]:
bow.shape

(174, 177)

In [45]:
bow[141]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [46]:
x = bow
y = df['labels'].values

In [47]:
len(x), len(y)

(174, 174)

In [48]:
list(zip(data,x,y))[10]

('Hello there!',
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0]),
 'hello_trigger')

In [49]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

In [50]:
encoder = LabelEncoder().fit(y)

In [51]:
 y_encoded = encoder.transform(y)

In [52]:
y_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [53]:
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.3, shuffle=True, random_state=0)

In [54]:
print(len(x_train), len(x_test), len(y_train), len(y_test))

121 53 121 53


In [55]:
model = LogisticRegression(multi_class='multinomial')

In [56]:
from sklearn.metrics import accuracy_score, confusion_matrix
model.fit(x_train,y_train)
pred = model.predict(x_test)
print(accuracy_score(y_pred=pred,y_true=y_test))
print(confusion_matrix(y_pred=pred,y_true=y_test))

0.9245283018867925
[[19  0  0  0]
 [ 1 10  1  0]
 [ 0  0 12  1]
 [ 0  1  0  8]]


/home/ackerman/anaconda3/envs/chatbot_nltk/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


In [57]:
hello = [
    "Hello",
    "Hi",
    "Hey",
    "Hi there",
    "Hey there",
    "Greetings",
    "Howdy",
    "Yo",
    "Hiya",
    "Hello there",
    "Well hello",
    "Hiya",
    "Hey buddy",
    "Hi folks",
    "Hi everyone",
    "Hi friends",
    "What's up",
    "Hey ya",
    "Good to see you",
    "Nice to see you"
]

In [58]:
responses_to_thank_you = [
    "You're welcome",
    "No problem",
    "No worries",
    "Don't mention it",
    "It was nothing",
    "My pleasure",
    "Anytime",
    "Sure thing",
    "You got it",
    "Glad to help",
    "Happy to help",
    "That's okay",
    "Not at all",
    "It's my pleasure",
    "I'm happy to assist",
    "It's no trouble at all",
    "I'm glad you liked it",
    "You're very welcome",
    "It's the least I could do",
    "Of course"
]

In [59]:
enjoy_messages = [
    "Enjoy!",
    "Have fun!",
    "Have a great time!",
    "Enjoy yourself!",
    "Have a blast!",
    "Make the most of it!",
    "Hope you have a good one!",
    "Wishing you a great time!",
    "Hope it's a good one!",
    "Have a good one!",
    "Hope you enjoy it!",
    "Make it a great one!",
    "Hope you have a fantastic time!",
    "Enjoy every moment!",
    "Make the most of your day!",
    "Wishing you lots of fun!",
    "Have an awesome time!",
    "Hope you have a wonderful time!"
]

In [60]:
import joblib
joblib.dump(model,open('../english_version/models/base_model.joblib','wb'))

In [61]:
import pickle
pickle.dump(encoder,open('../english_version/objects/base_encoder','wb'))

In [62]:
import pickle
joblib.dump(cv,open('../english_version/objects/base_vectorizer','wb'))

In [63]:
encoder.inverse_transform([0])

array(['hello_trigger'], dtype=object)

In [64]:
# while True:
#   import random
#   import numpy as np
#   texto = input()
#   matrix = cv.transform([texto]).toarray()
#   pred = model.predict(matrix)
#   pred_label = encoder.inverse_transform(pred)
#   if pred_label == np.array('hello_trigger'):
#     print(f'{random.choice(hello)} what can i do for you')
#   elif pred_label == np.array('info_trigger'):
#     print('of corse muy functions are...')
#   elif pred_label == np.array('recomm_trigger'):
#     print(f'sure i left you a buttom to go movies system {random.choice(enjoy_messages)}')
#   elif pred_label == np.array('thanks_trigger'):
#     print(f'{random.choice(responses_to_thank_you)}')