In [1]:
import pandas as pd
from nltk import word_tokenize
import numpy as np
# import imp
# imp.reload(module)

In [2]:
df = pd.read_excel('../data/raw_data/excel chat.xlsx')
df

saludos  \
0                                 ¡Hola!   
1                           Buenos días.   
2                         Buenas tardes.   
3                         Buenas noches.   
4                              ¿Qué tal?   
..                                   ...   
95      ¡Hola, ¿cómo te va con tu humor?   
96          ¡Hola, ¿cómo estás de humor?   
97      ¡Hola, ¿cómo estás de humor hoy?   
98  ¡Hola, ¿cómo te encuentras de humor?   
99                                  ```    

                               presentaciones  \
0                             Hola, soy Juan.   
1                Me llamo María, mucho gusto.   
2                  Encantado, me llamo David.   
3                       Soy Ana, ¿cómo estás?   
4   Mi nombre es Carlos, un placer conocerte.   
..                                        ...   
95                      Hola, me dicen Pablo.   
96                     Soy Isabel, un placer.   
97                   Puedes llamarme Juanita.   
98               Hola, me llaman Laura Sofía.   
99                    Soy David, ¿cómo estás?   

                                 informacion  \
0        ¿Cuál es tu mecanismo de operación?   
1        ¿Cuál es tu modo de funcionamiento?   
2     ¿Cómo trabajas en términos de proceso?   
3   ¿De qué manera llevas a cabo tus tareas?   
4           ¿Cuál es tu método de ejecución?   
..                                       ...   
95                     ¿Qué talentos tienes?   
96                     ¿En qué eres experto?   
97                             ¿Qué dominas?   
98        ¿Qué puedes hacer mejor que otros?   
99                    ¿En qué áreas brillas?   

                                      recomendaciones  
0   ¿Tienes alguna película o serie que recomendar...  
1   ¿Podrías sugerirme una buena película para ver...  
2   ¿Qué película o serie me recomendarías para re...  
3   ¿Conoces alguna película emocionante que valga...  
4   ¿Cuál es tu serie de televisión favorita en es...  
..                                                ...  
95              ¿Qué me sugieres ver en este momento?  
96             ¿Qué está bueno para ver en streaming?  
97   ¿Algún programa que me atrape desde el princi...  
98        ¿Qué serie o película me recomendarías hoy?  
99    ¿Algún título interesante para ver en pantalla?  

[100 rows x 4 columns]

In [3]:
from module_pro import *
lista = get_tokens('¿Cuál es tu mecanismo de operación?')  
lista

[nltk_data] Downloading package punkt to /home/ackerman/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/ackerman/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Error loading corpus: Package 'corpus' not found in index
[nltk_data] Error loading stem: Package 'stem' not found in index


['cual', 'es', 'tu', 'mecanismo', 'de', 'operacion']

In [4]:
from module_pro import *
lista = get_tokens(['hola como estas','bienvbenidos a la pryeba','texrto a tokenizar'])  
lista

entraste al if de df


[['hola', 'como', 'estas'],
 ['bienvbenidos', 'a', 'la', 'pryeba'],
 ['texrto', 'a', 'tokenizar']]

In [5]:
nostops('¿Cuál es tu mecanismo de operación?',df=False)

['mecanismo', 'operacion']

In [6]:
stops = nostops(df['informacion'],df=True)
stops

[['mecanismo', 'operacion'],
 ['modo', 'funcionamiento'],
 ['trabajas', 'terminos', 'proceso'],
 ['manera', 'llevas', 'cabo', 'tareas'],
 ['metodo', 'ejecucion'],
 ['operas', 'practica'],
 ['sistema', 'funcionamiento'],
 ['proceso', 'sigues', 'realizar', 'funciones'],
 ['organizas', 'realizar', 'actividades'],
 ['procedimiento', 'llevar', 'cabo', 'funciones'],
 ['puedes', 'echarme', 'mano'],
 ['puedas', 'colaborar'],
 ['importaria', 'prestarme', 'ayuda'],
 ['podrias', 'asistirme', 'tema'],
 ['podrias', 'hacer', 'favor', 'ayudarme'],
 ['tiempo', 'brindarme', 'apoyo'],
 ['puedo', 'contar', 'contigo', 'resolver'],
 ['serias', 'tan', 'amable', 'ofrecerme', 'ayuda'],
 ['disponible', 'colaborar', 'proyecto'],
 ['podrias', 'orientar'],
 ['podrias', 'compartir', 'experiencia', 'ayudarme'],
 ['bueno', 'puedas', 'ayudarme'],
 ['animarias', 'echarme', 'mano'],
 ['algun', 'consejo', 'resolver', 'situacion'],
 ['podrias', 'darme', 'empujon', 'tarea'],
 ['ayudas', 'encontrar', 'solucion'],
 ['podria

In [7]:
leems = lematize('¿Cuál es tu mecanismo de operación?',df=False)
leems

['mecan', 'oper']

In [8]:
leems = lematize(df['informacion'],df=True)
leems

[['mecan', 'oper'],
 ['mod', 'funcion'],
 ['trabaj', 'termin', 'proces'],
 ['maner', 'llev', 'cab', 'tar'],
 ['metod', 'ejecucion'],
 ['oper', 'practic'],
 ['sistem', 'funcion'],
 ['proces', 'sig', 'realiz', 'funcion'],
 ['organiz', 'realiz', 'activ'],
 ['proced', 'llev', 'cab', 'funcion'],
 ['pued', 'echarm', 'man'],
 ['pued', 'colabor'],
 ['importari', 'prest', 'ayud'],
 ['podri', 'asist', 'tem'],
 ['podri', 'hac', 'favor', 'ayud'],
 ['tiemp', 'brind', 'apoy'],
 ['pued', 'cont', 'contig', 'resolv'],
 ['seri', 'tan', 'amabl', 'ofrec', 'ayud'],
 ['dispon', 'colabor', 'proyect'],
 ['podri', 'orient'],
 ['podri', 'compart', 'experient', 'ayud'],
 ['buen', 'pued', 'ayud'],
 ['animari', 'echarm', 'man'],
 ['algun', 'consej', 'resolv', 'situacion'],
 ['podri', 'darm', 'empujon', 'tare'],
 ['ayud', 'encontr', 'solucion'],
 ['podri', 'darm', 'opinion', 'proced'],
 ['gustari', 'particip', 'proyect', 'junt'],
 ['dispuest', 'trabaj', 'equip', 'resolv'],
 ['algun', 'ide', 'solucion'],
 ['pued', '

In [9]:
model = generate_model(df['informacion'],df=True)
bow_text('¿Cuál es tu mecanismo de operación?',bow_model=model,df=False)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((4,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
model = generate_model(df['informacion'],df=True)
bow_text(df['informacion'],bow_model=model,df=True)

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.

In [12]:
model.get_feature_names_out()

array(['abord', 'aclar', 'activ', 'algun', 'amabl', 'animari', 'apoy',
       'aqui', 'are', 'asist', 'asunt', 'ayud', 'bien', 'brill', 'brind',
       'buen', 'cab', 'capaz', 'colabor', 'compart', 'conmig', 'consej',
       'cont', 'contig', 'cual', 'cuent', 'da', 'darl', 'darm', 'das',
       'dat', 'dec', 'destac', 'detall', 'dispon', 'dispuest', 'domin',
       'echarm', 'echas', 'ejecucion', 'empujon', 'encontr', 'entend',
       'equip', 'esper', 'exact', 'experient', 'expert', 'explic',
       'favor', 'fresc', 'fuert', 'funcion', 'gustari', 'habil', 'hac',
       'ide', 'implic', 'importari', 'inclu', 'info', 'inform',
       'involucr', 'junt', 'llev', 'man', 'maner', 'mas', 'mecan',
       'mejor', 'metod', 'mir', 'mod', 'necesit', 'ofrec', 'oper',
       'opinion', 'organiz', 'orient', 'particip', 'perspect', 'podri',
       'practic', 'prest', 'problem', 'proced', 'proces', 'proporcion',
       'proposit', 'proyect', 'pued', 'punt', 'realiz', 'recurs',
       'resolv', 'res

In [13]:
generate_df(df['informacion'],bow_model=model)

100 100 100 100


raw_data  \
0        ¿Cuál es tu mecanismo de operación?   
1        ¿Cuál es tu modo de funcionamiento?   
2     ¿Cómo trabajas en términos de proceso?   
3   ¿De qué manera llevas a cabo tus tareas?   
4           ¿Cuál es tu método de ejecución?   
..                                       ...   
95                     ¿Qué talentos tienes?   
96                     ¿En qué eres experto?   
97                             ¿Qué dominas?   
98        ¿Qué puedes hacer mejor que otros?   
99                    ¿En qué áreas brillas?   

                                             tokens  \
0          [cual, es, tu, mecanismo, de, operacion]   
1          [cual, es, tu, modo, de, funcionamiento]   
2       [como, trabajas, en, terminos, de, proceso]   
3   [de, que, manera, llevas, a, cabo, tus, tareas]   
4             [cual, es, tu, metodo, de, ejecucion]   
..                                              ...   
95                          [que, talentos, tienes]   
96                         [en, que, eres, experto]   
97                                   [que, dominas]   
98          [que, puedes, hacer, mejor, que, otros]   
99                        [en, que, areas, brillas]   

                    no stops words              lematization  \
0           [mecanismo, operacion]             [mecan, oper]   
1           [modo, funcionamiento]            [mod, funcion]   
2    [trabajas, terminos, proceso]  [trabaj, termin, proces]   
3   [manera, llevas, cabo, tareas]   [maner, llev, cab, tar]   
4              [metodo, ejecucion]        [metod, ejecucion]   
..                             ...                       ...   
95                      [talentos]                  [talent]   
96                       [experto]                  [expert]   
97                       [dominas]                   [domin]   
98          [puedes, hacer, mejor]        [pued, hac, mejor]   
99                [areas, brillas]              [are, brill]   

                                           text coded  
0   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                ...  
95  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
96  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
97  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
98  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
99  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...  

[100 rows x 5 columns]

In [14]:
# @codificacion de un texto simple
#paso 1 importar modulo bower para obtener data
from concverter2_0 import bower
#paso 2 obtener tokens,stops y lemms
tokens, stops, lemms = bower().text(text='!Hola!, como has estado? yo bien muchas gracias')
#paso 3 crear modelo bower con sklearn y ajustarlo con tus lemms de todo tu data
from sklearn.feature_extraction.text import CountVectorizer
bower_model = CountVectorizer()
bower_model.fit(lemms)
#paso 4 transoformar tus leems por elemento de tu data con el modelo ajustado 
coded = bower_model.transform(lemms)
#paso 5 observar tus features para codificar texto
bower_model.get_feature_names_out()
#paso 6 convertirlo en array para observarlo en forma de matriz
coded = coded.toarray()

[nltk_data] Downloading package punkt to /home/ackerman/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/ackerman/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Error loading corpus: Package 'corpus' not found in index
[nltk_data] Error loading stem: Package 'stem' not found in index


In [15]:
print('tokens: ', tokens)
print('no stop words: ', tokens)
print('lemmatized : ', lemms)
print('features to code: ', bower_model.get_feature_names_out())
print('texto codificado: ', coded)

tokens:  ['hola', 'como', 'has', 'estado', 'yo', 'bien', 'muchas', 'gracias']
no stop words:  ['hola', 'como', 'has', 'estado', 'yo', 'bien', 'muchas', 'gracias']
lemmatized :  ['hol', 'bien', 'much', 'graci']
features to code:  ['bien' 'graci' 'hol' 'much']
texto codificado:  [[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
