In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/raw_data/afirnation_data.csv')
df

text  afirmacion
0         Es cierto           1
1    Indudablemente           1
2          Sin duda           1
3      Es innegable           1
4         Es verdad           1
..              ...         ...
195       me cansan           0
196   preferible no           0
197         paso de           0
198            paso           0
199            safo           0

[200 rows x 2 columns]

In [3]:
from module_pro import generate_model, generate_df #slef modulo
from sklearn.feature_extraction.text import CountVectorizer

[nltk_data] Downloading package punkt to /home/ackerman/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/ackerman/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Error loading corpus: Package 'corpus' not found in index
[nltk_data] Error loading stem: Package 'stem' not found in index


In [4]:
bowler_model = CountVectorizer() #generamos modelo de lematization

In [32]:
full_data = (' ').join(df['text'].tolist())
from unidecode import unidecode
import re
full_data = unidecode(full_data)
full_data = full_data.lower()
full_data

'es cierto indudablemente sin duda es innegable es verdad asi es no hay discusion al respecto totalmente de acuerdo absolutamente correcto sin lugar a dudas por supuesto de hecho es evidente no cabe duda exactamente asi es como lo veo estoy de acuerdo contigo sin ninguna sombra de duda eso esta claro no es cierto de ninguna manera no estoy de acuerdo es falso no es asi eso no es correcto no estoy convencido no estoy seguro de eso no es verdad no lo creo no es posible no estoy de acuerdo en absoluto no veo las cosas de esa manera eso es incorrecto no es asi como lo veo no estoy de acuerdo contigo en absoluto no estoy conforme no estoy convencido de eso no me suena correcto no estoy seguro de que sea asi ?podrias por favor brindarme tu ayuda? ?serias tan amable de ayudarme con esto? ?podrias guiarme un poco en este asunto? ?me podrias echar una mano con esto? ?puedo contar contigo para obtener ayuda? ?te importaria asistirme con este problema? ?serias tan amable de prestarme tu ayuda? ?p

In [6]:
def quitar_no_letras_con_espacios(texto):
    return re.sub(r'[^a-zA-Z\s]', '', texto)

full_data_clean = quitar_no_letras_con_espacios(full_data)
full_data_clean

'es cierto indudablemente sin duda es innegable es verdad asi es no hay discusion al respecto totalmente de acuerdo absolutamente correcto sin lugar a dudas por supuesto de hecho es evidente no cabe duda exactamente asi es como lo veo estoy de acuerdo contigo sin ninguna sombra de duda eso esta claro no es cierto de ninguna manera no estoy de acuerdo es falso no es asi eso no es correcto no estoy convencido no estoy seguro de eso no es verdad no lo creo no es posible no estoy de acuerdo en absoluto no veo las cosas de esa manera eso es incorrecto no es asi como lo veo no estoy de acuerdo contigo en absoluto no estoy conforme no estoy convencido de eso no me suena correcto no estoy seguro de que sea asi podrias por favor brindarme tu ayuda serias tan amable de ayudarme con esto podrias guiarme un poco en este asunto me podrias echar una mano con esto puedo contar contigo para obtener ayuda te importaria asistirme con este problema serias tan amable de prestarme tu ayuda podrias darme or

In [7]:
from nltk import word_tokenize
import nltk
from nltk.stem import SnowballStemmer
stemmer = SnowballStemmer('spanish')

In [8]:
def stemizar(tokens):
    stemms = []
    for token in tokens:
        stemms.append(stemmer.stem(token))
    return stemms

In [9]:
tok = word_tokenize(full_data_clean)
lem = stemizar(tok)
print(tok,lem,sep='*****************\n')


['es', 'cierto', 'indudablemente', 'sin', 'duda', 'es', 'innegable', 'es', 'verdad', 'asi', 'es', 'no', 'hay', 'discusion', 'al', 'respecto', 'totalmente', 'de', 'acuerdo', 'absolutamente', 'correcto', 'sin', 'lugar', 'a', 'dudas', 'por', 'supuesto', 'de', 'hecho', 'es', 'evidente', 'no', 'cabe', 'duda', 'exactamente', 'asi', 'es', 'como', 'lo', 'veo', 'estoy', 'de', 'acuerdo', 'contigo', 'sin', 'ninguna', 'sombra', 'de', 'duda', 'eso', 'esta', 'claro', 'no', 'es', 'cierto', 'de', 'ninguna', 'manera', 'no', 'estoy', 'de', 'acuerdo', 'es', 'falso', 'no', 'es', 'asi', 'eso', 'no', 'es', 'correcto', 'no', 'estoy', 'convencido', 'no', 'estoy', 'seguro', 'de', 'eso', 'no', 'es', 'verdad', 'no', 'lo', 'creo', 'no', 'es', 'posible', 'no', 'estoy', 'de', 'acuerdo', 'en', 'absoluto', 'no', 'veo', 'las', 'cosas', 'de', 'esa', 'manera', 'eso', 'es', 'incorrecto', 'no', 'es', 'asi', 'como', 'lo', 'veo', 'no', 'estoy', 'de', 'acuerdo', 'contigo', 'en', 'absoluto', 'no', 'estoy', 'conforme', 'no', '

In [10]:
bowler_model.fit(lem)
bowler_model.vocabulary_ #vocabulario de lematization de toda la data

{'es': 92,
 'ciert': 43,
 'indud': 127,
 'sin': 215,
 'dud': 84,
 'inneg': 129,
 'verd': 248,
 'asi': 23,
 'no': 157,
 'hay': 120,
 'discusion': 77,
 'al': 14,
 'respect': 204,
 'total': 240,
 'de': 68,
 'acuerd': 8,
 'absolut': 2,
 'correct': 60,
 'lug': 139,
 'por': 174,
 'supuest': 230,
 'hech': 121,
 'evident': 104,
 'cab': 37,
 'exact': 105,
 'com': 46,
 'lo': 137,
 'veo': 246,
 'estoy': 103,
 'contig': 58,
 'ningun': 156,
 'sombr': 223,
 'eso': 96,
 'esta': 99,
 'clar': 44,
 'maner': 142,
 'fals': 109,
 'convenc': 59,
 'segur': 212,
 'cre': 62,
 'posibl': 175,
 'en': 89,
 'las': 136,
 'cos': 61,
 'esa': 93,
 'incorrect': 125,
 'conform': 51,
 'me': 144,
 'suen': 225,
 'que': 193,
 'sea': 210,
 'podri': 172,
 'favor': 112,
 'brind': 33,
 'tu': 242,
 'ayud': 30,
 'seri': 213,
 'tan': 231,
 'amabl': 17,
 'con': 49,
 'esto': 102,
 'gui': 116,
 'un': 243,
 'poc': 171,
 'este': 101,
 'asunt': 26,
 'echar': 86,
 'una': 244,
 'man': 140,
 'pued': 192,
 'cont': 56,
 'par': 163,
 'obten': 

In [11]:
bowler_model.get_feature_names_out()

array(['abiert', 'abord', 'absolut', 'aburr', 'acces', 'acerc', 'aclar',
       'aconsej', 'acuerd', 'adecu', 'adicional', 'agradari', 'agradezc',
       'ahor', 'al', 'algo', 'algun', 'amabl', 'ampli', 'antes', 'apreci',
       'apropi', 'arreglarmel', 'asi', 'asist', 'asistent', 'asunt',
       'atencion', 'autoriz', 'avientam', 'ayud', 'ayudart', 'bien',
       'brind', 'brindart', 'buen', 'busc', 'cab', 'camin', 'cans',
       'capacit', 'cas', 'causart', 'ciert', 'clar', 'colabor', 'com',
       'compart', 'complet', 'con', 'confiabl', 'conform', 'conmig',
       'consej', 'consider', 'consult', 'cont', 'context', 'contig',
       'convenc', 'correct', 'cos', 'cre', 'cual', 'cuent', 'dar', 'darm',
       'dat', 'de', 'deb', 'dec', 'decid', 'decision', 'dedic', 'depend',
       'desagrad', 'detall', 'discusion', 'disgust', 'dispong',
       'disposicion', 'diviert', 'document', 'dond', 'dud', 'echam',
       'echar', 'efect', 'eleg', 'en', 'encontr', 'entend', 'es', 'esa',
       '

In [12]:
df

text  afirmacion
0         Es cierto           1
1    Indudablemente           1
2          Sin duda           1
3      Es innegable           1
4         Es verdad           1
..              ...         ...
195       me cansan           0
196   preferible no           0
197         paso de           0
198            paso           0
199            safo           0

[200 rows x 2 columns]

In [13]:
def limpia_texto(text):
    texto_limpio = re.sub(r'[^a-zA-Z\s]', '', text)
    sin_acentos = unidecode(texto_limpio)
    minusculas = sin_acentos.lower()
    return minusculas

In [14]:
df

text  afirmacion
0         Es cierto           1
1    Indudablemente           1
2          Sin duda           1
3      Es innegable           1
4         Es verdad           1
..              ...         ...
195       me cansan           0
196   preferible no           0
197         paso de           0
198            paso           0
199            safo           0

[200 rows x 2 columns]

In [15]:
df['text_clean'] = df.apply(lambda x: (limpia_texto(x['text'])),axis=1)
df['tokens'] = df.apply(lambda x: (word_tokenize(x['text_clean'])),axis=1)
df['lemms'] = df.apply(lambda x: (stemizar(x['tokens'])),axis=1)

In [16]:
matrices_list = []
for lem in df['lemms']:
    matrices = bowler_model.transform(lem).toarray()
    no_matrices = len(matrices)
    shape_matrix = matrices[0].shape
    sum_matrices = np.zeros(shape_matrix)
    for matrix in matrices:
        sum_matrices = sum_matrices + matrix
    matrices_list.append(sum_matrices)
matrices_list

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 

In [17]:
df

text  afirmacion      text_clean            tokens  \
0         Es cierto           1       es cierto      [es, cierto]   
1    Indudablemente           1  indudablemente  [indudablemente]   
2          Sin duda           1        sin duda       [sin, duda]   
3      Es innegable           1    es innegable   [es, innegable]   
4         Es verdad           1       es verdad      [es, verdad]   
..              ...         ...             ...               ...   
195       me cansan           0       me cansan      [me, cansan]   
196   preferible no           0   preferible no  [preferible, no]   
197         paso de           0         paso de        [paso, de]   
198            paso           0            paso            [paso]   
199            safo           0            safo            [safo]   

            lemms  
0     [es, ciert]  
1         [indud]  
2      [sin, dud]  
3     [es, inneg]  
4      [es, verd]  
..            ...  
195    [me, cans]  
196  [prefer, no]  
197     [pas, de]  
198         [pas]  
199         [saf]  

[200 rows x 5 columns]

In [18]:
df['matrices'] = matrices_list
df

text  afirmacion      text_clean            tokens  \
0         Es cierto           1       es cierto      [es, cierto]   
1    Indudablemente           1  indudablemente  [indudablemente]   
2          Sin duda           1        sin duda       [sin, duda]   
3      Es innegable           1    es innegable   [es, innegable]   
4         Es verdad           1       es verdad      [es, verdad]   
..              ...         ...             ...               ...   
195       me cansan           0       me cansan      [me, cansan]   
196   preferible no           0   preferible no  [preferible, no]   
197         paso de           0         paso de        [paso, de]   
198            paso           0            paso            [paso]   
199            safo           0            safo            [safo]   

            lemms                                           matrices  
0     [es, ciert]  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1         [indud]  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2      [sin, dud]  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3     [es, inneg]  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4      [es, verd]  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..            ...                                                ...  
195    [me, cans]  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
196  [prefer, no]  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
197     [pas, de]  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
198         [pas]  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
199         [saf]  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[200 rows x 6 columns]

In [19]:
df_proccesed = df[['text','matrices','afirmacion']]
df_proccesed

text                                           matrices  \
0         Es cierto  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1    Indudablemente  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2          Sin duda  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3      Es innegable  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4         Es verdad  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
..              ...                                                ...   
195       me cansan  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
196   preferible no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
197         paso de  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
198            paso  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
199            safo  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

     afirmacion  
0             1  
1             1  
2             1  
3             1  
4             1  
..          ...  
195           0  
196           0  
197           0  
198           0  
199           0  

[200 rows x 3 columns]

In [20]:
df_proccesed['afirmacion']=df_proccesed['afirmacion'].astype('float32')

/tmp/ipykernel_31559/3282881655.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_proccesed['afirmacion']=df_proccesed['afirmacion'].astype('float32')


#Construimos el modelo naive steivs

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB


In [22]:
x_data = df['matrices']
y_data = np.asarray(df['afirmacion'],dtype='float32')

In [23]:
x_data.shape, y_data.shape

((200,), (200,))

In [24]:
x_data[0], y_data[0]

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x_data,y_data,random_state=42,test_size=0.3)

In [26]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((140,), (60,), (140,), (60,))

In [27]:
clasificator_model = MultinomialNB()
clasificator_model.fit(x_train.tolist(),y_train)

MultinomialNB()

In [28]:
#metricas
y_predict = clasificator_model.predict(x_test.tolist())
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred=y_predict))
print(accuracy_score(y_test,y_pred=y_predict))

[[28  1]
 [ 8 23]]
0.85


In [29]:
import joblib
joblib.dump(clasificator_model,'../models/afirmation_model.joblib')

['../models/afirmation_model.joblib']

In [30]:
def prediccion(modelo_prediccion):
    texto = input(f'you: ')
    texto = limpia_texto(texto)
    tokens = word_tokenize(texto)
    leems = stemizar(tokens)
    matriz = bowler_model.transform(leems).toarray()
    predict = modelo_prediccion.predict(matriz)
    #print(modelo_prediccion.predict_proba(matriz))
    print(predict)

In [31]:
while True:
    prediccion(clasificator_model)

[0. 0.]
[1. 1.]
[0. 1. 1.]
[0. 1. 1.]
[0. 0. 1. 0. 0.]
[0. 0. 0.]
[0. 0. 1. 1.]
[0. 0. 1.]


ValueError: Found array with 0 sample(s) (shape=(0, 251)) while a minimum of 1 is required by MultinomialNB.

In [ ]:
df_proccesed

text                                           matrices  \
0         Es cierto  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1    Indudablemente  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2          Sin duda  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3      Es innegable  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4         Es verdad  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
..              ...                                                ...   
195       me cansan  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
196   preferible no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
197         paso de  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
198            paso  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
199            safo  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

     afirmacion  
0             1  
1             1  
2             1  
3             1  
4             1  
..          ...  
195           0  
196           0  
197           0  
198           0  
199           0  

[200 rows x 3 columns]