In [52]:
import pandas as pd
import numpy as np
from module_pro import generate_model,generate_df

In [53]:
df = pd.read_excel('../data/raw_data/excel chat.xlsx')
df

saludos  \
0                                 ¡Hola!   
1                           Buenos días.   
2                         Buenas tardes.   
3                         Buenas noches.   
4                              ¿Qué tal?   
..                                   ...   
95      ¡Hola, ¿cómo te va con tu humor?   
96          ¡Hola, ¿cómo estás de humor?   
97      ¡Hola, ¿cómo estás de humor hoy?   
98  ¡Hola, ¿cómo te encuentras de humor?   
99                                  ```    

                               presentaciones  \
0                             Hola, soy Juan.   
1                Me llamo María, mucho gusto.   
2                  Encantado, me llamo David.   
3                       Soy Ana, ¿cómo estás?   
4   Mi nombre es Carlos, un placer conocerte.   
..                                        ...   
95                      Hola, me dicen Pablo.   
96                     Soy Isabel, un placer.   
97                   Puedes llamarme Juanita.   
98               Hola, me llaman Laura Sofía.   
99                    Soy David, ¿cómo estás?   

                                 informacion  \
0        ¿Cuál es tu mecanismo de operación?   
1        ¿Cuál es tu modo de funcionamiento?   
2     ¿Cómo trabajas en términos de proceso?   
3   ¿De qué manera llevas a cabo tus tareas?   
4           ¿Cuál es tu método de ejecución?   
..                                       ...   
95                     ¿Qué talentos tienes?   
96                     ¿En qué eres experto?   
97                             ¿Qué dominas?   
98        ¿Qué puedes hacer mejor que otros?   
99                    ¿En qué áreas brillas?   

                                      recomendaciones  
0   ¿Tienes alguna película o serie que recomendar...  
1   ¿Podrías sugerirme una buena película para ver...  
2   ¿Qué película o serie me recomendarías para re...  
3   ¿Conoces alguna película emocionante que valga...  
4   ¿Cuál es tu serie de televisión favorita en es...  
..                                                ...  
95              ¿Qué me sugieres ver en este momento?  
96             ¿Qué está bueno para ver en streaming?  
97   ¿Algún programa que me atrape desde el princi...  
98        ¿Qué serie o película me recomendarías hoy?  
99    ¿Algún título interesante para ver en pantalla?  

[100 rows x 4 columns]

In [54]:
text=[]
text.extend(df['saludos'])
text.extend(df['presentaciones'])
text.extend(df['informacion'])
text.extend(df['recomendaciones'])

text

['¡Hola!',
 'Buenos días.',
 'Buenas tardes.',
 'Buenas noches.',
 '¿Qué tal?',
 '¿Cómo estás?',
 '¿Qué haces?',
 '¿Cómo va todo?',
 '¿Cómo te encuentras?',
 '¿Qué hay de nuevo?',
 '¿Qué pasa?',
 '¿Qué cuentas?',
 '¿Qué onda?',
 '¿Cómo te va?',
 '¿Cómo te sientes?',
 '¡Saludos!',
 '¡Buen día!',
 '¡Hola, qué tal!',
 '¡Hola, ¿qué hubo?',
 '¡Hey!',
 '¡Hola, amigo!',
 '¡Buenas!',
 '¡Qué gusto verte!',
 '¡Hola, buenos días!',
 '¡Hola, buenas tardes!',
 '¡Hola, buenas noches!',
 '¿Cómo andas?',
 '¿Qué tal va todo?',
 '¿Qué tal estás?',
 '¿Qué hay de tu vida?',
 '¿Cómo te trata la vida?',
 '¿Cómo te va en todo?',
 '¡Hola, cómo estás!',
 '¡Qué alegría verte!',
 '¡Hola, qué tal estás!',
 '¡Hola, cómo has estado!',
 '¡Hola, ¿cómo te va?',
 '¡Hola, ¿cómo estás hoy?',
 '¡Buenas, ¿cómo estás?',
 '¡Hola, ¿qué cuentas?',
 '¡Hola, ¿qué tal estás hoy?',
 '¡Hola, ¿qué tal te encuentras?',
 '¡Hola, ¿cómo te sientes?',
 '¡Hola, ¿cómo lo llevas?',
 '¡Hola, ¿cómo lo has pasado?',
 '¡Hola, ¿cómo te ha ido?',

In [55]:
len(text)

400

In [56]:
df_proccesed = pd.DataFrame({'text':text,
             'target_saludo':0,
             'target_presentacion':0,
             'target informacion':0,
             'target recomendacion':0})

In [57]:
df_proccesed

text  target_saludo  \
0                                               ¡Hola!              0   
1                                         Buenos días.              0   
2                                       Buenas tardes.              0   
3                                       Buenas noches.              0   
4                                            ¿Qué tal?              0   
..                                                 ...            ...   
395              ¿Qué me sugieres ver en este momento?              0   
396             ¿Qué está bueno para ver en streaming?              0   
397   ¿Algún programa que me atrape desde el princi...              0   
398        ¿Qué serie o película me recomendarías hoy?              0   
399    ¿Algún título interesante para ver en pantalla?              0   

     target_presentacion  target informacion  target recomendacion  
0                      0                   0                     0  
1                      0                   0                     0  
2                      0                   0                     0  
3                      0                   0                     0  
4                      0                   0                     0  
..                   ...                 ...                   ...  
395                    0                   0                     0  
396                    0                   0                     0  
397                    0                   0                     0  
398                    0                   0                     0  
399                    0                   0                     0  

[400 rows x 5 columns]

In [58]:
df_proccesed['target_saludo'].iloc[0:100] = 1
df_proccesed['target_presentacion'].iloc[100:200] = 1
df_proccesed['target informacion'].iloc[200:300] = 1
df_proccesed['target recomendacion'].iloc[300:400] = 1

/tmp/ipykernel_12402/1175268902.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_proccesed['target_saludo'].iloc[0:100] = 1
/tmp/ipykernel_12402/1175268902.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice

In [59]:
df_proccesed.iloc[300:400]

text  target_saludo  \
300  ¿Tienes alguna película o serie que recomendar...              0   
301  ¿Podrías sugerirme una buena película para ver...              0   
302  ¿Qué película o serie me recomendarías para re...              0   
303  ¿Conoces alguna película emocionante que valga...              0   
304  ¿Cuál es tu serie de televisión favorita en es...              0   
..                                                 ...            ...   
395              ¿Qué me sugieres ver en este momento?              0   
396             ¿Qué está bueno para ver en streaming?              0   
397   ¿Algún programa que me atrape desde el princi...              0   
398        ¿Qué serie o película me recomendarías hoy?              0   
399    ¿Algún título interesante para ver en pantalla?              0   

     target_presentacion  target informacion  target recomendacion  
300                    0                   0                     1  
301                    0                   0                     1  
302                    0                   0                     1  
303                    0                   0                     1  
304                    0                   0                     1  
..                   ...                 ...                   ...  
395                    0                   0                     1  
396                    0                   0                     1  
397                    0                   0                     1  
398                    0                   0                     1  
399                    0                   0                     1  

[100 rows x 5 columns]

In [60]:
# Entendido, aquí tienes la tabla actualizada con 200 oraciones:

# | Texto                                               | Saludo | Presentación | Información | Recomendación |
# |-----------------------------------------------------|--------|--------------|-------------|---------------|
# | Hola, ¿cómo estás?                                 | 1      | 0            | 0           | 0             |
# | Buen día, soy María. ¿Podrías recomendarme una serie? | 1      | 1            | 0           | 1             |
# | ¡Hola! Me llamo Carlos, ¿me podrías decir dónde está la estación de tren? | 1      | 1            | 1           | 0             |
# | Buenos días, ¿qué tal?                              | 1      | 0            | 0           | 0             |
# | ¿Qué onda? Soy Laura, ¿me puedes recomendar una película? | 1      | 1            | 0           | 1             |
# | Hola, mi nombre es Juan. ¿Podrías darme información sobre el horario de la película? | 1      | 1            | 1           | 0             |
# | Buenas tardes, ¿cómo va todo?                       | 1      | 0            | 0           | 0             |
# | ¡Hola! Soy Ana. ¿Me podrías recomendar una serie?  | 1      | 1            | 0           | 1             |
# | ¿Qué tal? Mi nombre es Marta. ¿Dónde puedo encontrar información sobre esa serie? | 1      | 1            | 1           | 0             |
# | Buen día, ¿cómo estás? ¿Me recomendarías una película? | 1      | 0            | 0           | 1             |
# | ¡Hola! ¿Qué tal? ¿Podrías recomendarme una película de comedia? | 1      | 0            | 0           | 1             |
# | Buenas tardes, me llamo Sofía. ¿Dónde puedo encontrar información sobre esa serie que mencionaste? | 1      | 1            | 1           | 0             |
# | Hola, ¿cómo estás? Soy Diego. ¿Podrías recomendarme una película de acción? | 1      | 1            | 0           | 1             |
# | ¿Qué hay de nuevo? Me llamo Andrea. ¿Me podrías decir a qué hora comienza la función de cine? | 1      | 1            | 1           | 0             |
# | Buen día, ¿cómo va todo? ¿Podrías recomendarme una serie de suspenso? | 1      | 0            | 0           | 1             |
# | ¡Hola! Soy Pedro. ¿Dónde puedo conseguir información sobre esa serie que me recomendaste? | 1      | 1            | 1           | 0             |
# | Hola, ¿qué tal? Me llamo Ana. ¿Podrías indicarme cómo llegar al cine más cercano? | 1      | 1            | 1           | 0             |
# | Buenas tardes, soy José. ¿Me recomendarías una película de ciencia ficción? | 1      | 1            | 0           | 1             |
# | ¿Cómo estás? Me llamo Carla. ¿Podrías sugerirme una serie de drama para ver este fin de semana? | 1      | 1            | 0           | 1             |
# | ¡Hola! ¿Qué tal? ¿Podrías darme información sobre esa película que mencionaste? | 1      | 0            | 1           | 0             |

# (Sigo añadiendo oraciones hasta completar 200)

In [61]:
# Texto,Saludo,Presentación,Información,Recomendación
# Hola, ¿cómo estás?,1,0,0,0
# Buen día, soy María. ¿Podrías recomendarme una serie?,1,1,0,1
# ¡Hola! Me llamo Carlos, ¿me podrías decir dónde está la estación de tren?,1,1,1,0
# Buenos días, ¿qué tal?,1,0,0,0
# ¿Qué onda? Soy Laura, ¿me puedes recomendar una película?,1,1,0,1
# Hola, mi nombre es Juan. ¿Podrías darme información sobre el horario de la película?,1,1,1,0
# Buenas tardes, ¿cómo va todo?,1,0,0,0
# ¡Hola! Soy Ana. ¿Me podrías recomendar una serie?,1,1,0,1
# ¿Qué tal? Mi nombre es Marta. ¿Dónde puedo encontrar información sobre esa serie?,1,1,1,0
# Buen día, ¿cómo estás? ¿Me recomendarías una película?,1,0,0,1
# ¡Hola! ¿Qué tal? ¿Podrías recomendarme una película de comedia?,1,0,0,1
# Buenas tardes, me llamo Sofía. ¿Dónde puedo encontrar información sobre esa serie que mencionaste?,1,1,1,0
# Hola, ¿cómo estás? Soy Diego. ¿Podrías recomendarme una película de acción?,1,1,0,1
# ¿Qué hay de nuevo? Me llamo Andrea. ¿Me podrías decir a qué hora comienza la función de cine?,1,1,1,0
# Buen día, ¿cómo va todo? ¿Podrías recomendarme una serie de suspenso?,1,0,0,1
# ¡Hola! Soy Pedro. ¿Dónde puedo conseguir información sobre esa serie que me recomendaste?,1,1,1,0
# Hola, ¿qué tal? Me llamo Ana. ¿Podrías indicarme cómo llegar al cine más cercano?,1,1,1,0
# Buenas tardes, soy José. ¿Me recomendarías una película de ciencia ficción?,1,1,0,1
# ¿Cómo estás? Me llamo Carla. ¿Podrías sugerirme una serie de drama para ver este fin de semana?,1,1,0,1
# ¡Hola! ¿Qué tal? ¿Podrías darme información sobre esa película que mencionaste?,1,0,1,0
# Hola, ¿cómo estás? ¿Qué serie me recomendarías ver?,1,0,0,1
# Buen día, soy Alejandro. ¿Podrías decirme dónde queda la tienda de películas más cercana?,1,1,1,0
# ¡Hola! Me llamo Lucía, ¿podrías recomendarme una película romántica?,1,1,0,1
# Buenos días, ¿cómo estás? ¿Podrías recomendarme una serie de comedia?,1,0,0,1
# Hola, mi nombre es Pablo. ¿Podrías decirme en qué cine están pasando esa película?,1,1,1,0
# Buenas tardes, ¿cómo te encuentras? ¿Podrías sugerirme una serie de misterio?,1,0,0,1
# ¡Hola! Soy Martina. ¿Dónde puedo encontrar información sobre esa película que mencionaste?,1,1,1,0
# Hola, ¿qué tal? ¿Podrías recomendarme una serie de terror?,1,0,0,1
# Buen día, soy Andrés. ¿Podrías darme información sobre la trama de esa película?,1,1,1,0
# ¡Hola! ¿Qué tal? ¿Me podrías decir dónde está la tienda de alquiler de películas?,1,0,1,0
# Buenos días, ¿cómo va tu día? ¿Podrías sugerirme una serie de acción?,1,0,0,1
# Hola, ¿cómo estás? Soy Laura. ¿Podrías recomendarme una película para ver esta noche?,1,1,0,1
# Buenas tardes, me llamo Diego. ¿Dónde puedo encontrar información sobre esa serie nueva?,1,1,1,0
# Hola, ¿qué tal? Soy María. ¿Podrías decirme qué película ganó el Oscar el año pasado?,1,1,1,0
# ¡Hola! Me llamo Carlos. ¿Podrías recomendarme una serie de ciencia ficción?,1,1,0,1
# Buenos días, ¿cómo te encuentras? ¿Podrías decirme en qué cine están pasando esa película de la que hablaste?,1,0,1,0
# Hola, ¿cómo estás? ¿Qué película me recomendarías ver este fin de semana?,1,0,0,1
# Buen día, soy Ana. ¿Dónde puedo encontrar información sobre esa serie de la que todo el mundo habla?,1,1,1,0


In [62]:
permutaciones = ['1234 , 1243 , 1324 , 1342 , 1423 , 1432 , 2134 , 2143 , 2314 , 2341 , 2413 , 2431 , 3124 , 3142 , 3214 , 3241 , 3412 , 3421 , 4123 , 4132 , 4213 , 4231 , 4312 , 4321']

In [63]:
df_proccesed

text  target_saludo  \
0                                               ¡Hola!              1   
1                                         Buenos días.              1   
2                                       Buenas tardes.              1   
3                                       Buenas noches.              1   
4                                            ¿Qué tal?              1   
..                                                 ...            ...   
395              ¿Qué me sugieres ver en este momento?              0   
396             ¿Qué está bueno para ver en streaming?              0   
397   ¿Algún programa que me atrape desde el princi...              0   
398        ¿Qué serie o película me recomendarías hoy?              0   
399    ¿Algún título interesante para ver en pantalla?              0   

     target_presentacion  target informacion  target recomendacion  
0                      0                   0                     0  
1                      0                   0                     0  
2                      0                   0                     0  
3                      0                   0                     0  
4                      0                   0                     0  
..                   ...                 ...                   ...  
395                    0                   0                     1  
396                    0                   0                     1  
397                    0                   0                     1  
398                    0                   0                     1  
399                    0                   0                     1  

[400 rows x 5 columns]

In [64]:
from module_pro import generate_model
model = generate_model(df_proccesed['text'],df=True)

In [65]:
model.vocabulary_

{'patrici': 220,
 'gan': 126,
 'hol': 140,
 'activ': 2,
 'involucr': 156,
 'hoy': 141,
 'disfrut': 81,
 'recomiend': 249,
 'detall': 76,
 'antoni': 22,
 'seman': 263,
 'domin': 85,
 'pedr': 222,
 'dat': 67,
 'colabor': 47,
 'interes': 155,
 'laur': 168,
 'sorprend': 277,
 'descubr': 73,
 'alejandr': 10,
 'sistem': 272,
 'gabriel': 125,
 'particip': 218,
 'grat': 130,
 'marc': 182,
 'prest': 230,
 'onda': 210,
 'tel': 290,
 'mod': 198,
 'jorn': 160,
 'sig': 269,
 'manuel': 181,
 'impresion': 150,
 'pen': 225,
 'histori': 139,
 'opinion': 212,
 'noch': 204,
 'merced': 191,
 'bas': 31,
 'silvi': 271,
 'reflexion': 251,
 'utiliz': 304,
 'agreg': 6,
 'darl': 64,
 'andas': 17,
 'miguel': 193,
 'real': 243,
 'albert': 8,
 'recomendari': 248,
 'pabl': 215,
 'sugier': 282,
 'solucion': 276,
 'carm': 41,
 'luci': 173,
 'despu': 74,
 'tard': 288,
 'list': 170,
 'reir': 252,
 'dia': 77,
 'fern': 115,
 'mari': 183,
 'dej': 72,
 'darm': 65,
 'dram': 86,
 'terror': 294,
 'noved': 206,
 'angel': 19,
 

In [66]:
len(model.get_feature_names_out()), len(set(model.get_feature_names_out())) # leems are already setted

(315, 315)

In [67]:
# from module_pro import generate_df
# text_coded = generate_df(df_proccesed['text'],bow_model=model)['text coded'] 

In [68]:
# df_proccesed['text coded'] = text_coded

In [69]:
# df_proccesed =df_proccesed[['text', 'text coded','target_saludo', 'target_presentacion', 'target informacion',
#        'target recomendacion']]

In [70]:
df_proccesed

text  target_saludo  \
0                                               ¡Hola!              1   
1                                         Buenos días.              1   
2                                       Buenas tardes.              1   
3                                       Buenas noches.              1   
4                                            ¿Qué tal?              1   
..                                                 ...            ...   
395              ¿Qué me sugieres ver en este momento?              0   
396             ¿Qué está bueno para ver en streaming?              0   
397   ¿Algún programa que me atrape desde el princi...              0   
398        ¿Qué serie o película me recomendarías hoy?              0   
399    ¿Algún título interesante para ver en pantalla?              0   

     target_presentacion  target informacion  target recomendacion  
0                      0                   0                     0  
1                      0                   0                     0  
2                      0                   0                     0  
3                      0                   0                     0  
4                      0                   0                     0  
..                   ...                 ...                   ...  
395                    0                   0                     1  
396                    0                   0                     1  
397                    0                   0                     1  
398                    0                   0                     1  
399                    0                   0                     1  

[400 rows x 5 columns]

In [71]:
df_proccesed['target'] = None

In [72]:
df_proccesed['target'] = df_proccesed.apply(lambda x:('saludo' if x['target_saludo'] == 1 else x['target']),axis=1)
df_proccesed['target'] = df_proccesed.apply(lambda x:('presentacion' if x['target_presentacion'] == 1 else x['target']),axis=1)
df_proccesed['target'] = df_proccesed.apply(lambda x:('informacion' if x['target informacion'] == 1 else x['target']),axis=1)
df_proccesed['target'] = df_proccesed.apply(lambda x:('recomendacion' if x['target recomendacion'] == 1 else x['target']),axis=1)

In [73]:
df_proccesed

text  target_saludo  \
0                                               ¡Hola!              1   
1                                         Buenos días.              1   
2                                       Buenas tardes.              1   
3                                       Buenas noches.              1   
4                                            ¿Qué tal?              1   
..                                                 ...            ...   
395              ¿Qué me sugieres ver en este momento?              0   
396             ¿Qué está bueno para ver en streaming?              0   
397   ¿Algún programa que me atrape desde el princi...              0   
398        ¿Qué serie o película me recomendarías hoy?              0   
399    ¿Algún título interesante para ver en pantalla?              0   

     target_presentacion  target informacion  target recomendacion  \
0                      0                   0                     0   
1                      0                   0                     0   
2                      0                   0                     0   
3                      0                   0                     0   
4                      0                   0                     0   
..                   ...                 ...                   ...   
395                    0                   0                     1   
396                    0                   0                     1   
397                    0                   0                     1   
398                    0                   0                     1   
399                    0                   0                     1   

            target  
0           saludo  
1           saludo  
2           saludo  
3           saludo  
4           saludo  
..             ...  
395  recomendacion  
396  recomendacion  
397  recomendacion  
398  recomendacion  
399  recomendacion  

[400 rows x 6 columns]

In [74]:
df_proccesed['target'] = df_proccesed.apply(lambda x:(1 if x['target_saludo'] == 1 else x['target']),axis=1)
df_proccesed['target'] = df_proccesed.apply(lambda x:(2 if x['target_presentacion'] == 1 else x['target']),axis=1)
df_proccesed['target'] = df_proccesed.apply(lambda x:(3 if x['target informacion'] == 1 else x['target']),axis=1)
df_proccesed['target'] = df_proccesed.apply(lambda x:(4 if x['target recomendacion'] == 1 else x['target']),axis=1)

In [75]:
df_proccesed

text  target_saludo  \
0                                               ¡Hola!              1   
1                                         Buenos días.              1   
2                                       Buenas tardes.              1   
3                                       Buenas noches.              1   
4                                            ¿Qué tal?              1   
..                                                 ...            ...   
395              ¿Qué me sugieres ver en este momento?              0   
396             ¿Qué está bueno para ver en streaming?              0   
397   ¿Algún programa que me atrape desde el princi...              0   
398        ¿Qué serie o película me recomendarías hoy?              0   
399    ¿Algún título interesante para ver en pantalla?              0   

     target_presentacion  target informacion  target recomendacion  target  
0                      0                   0                     0       1  
1                      0                   0                     0       1  
2                      0                   0                     0       1  
3                      0                   0                     0       1  
4                      0                   0                     0       1  
..                   ...                 ...                   ...     ...  
395                    0                   0                     1       4  
396                    0                   0                     1       4  
397                    0                   0                     1       4  
398                    0                   0                     1       4  
399                    0                   0                     1       4  

[400 rows x 6 columns]

In [76]:
df_proccesed.dtypes

text                    object
target_saludo            int64
target_presentacion      int64
target informacion       int64
target recomendacion     int64
target                   int64
dtype: object

In [123]:
from module_pro import generate_model, generate_df
bowler_model = generate_model(df_proccesed['text'],df=True) #modelo bowler
df_generated = generate_df(df_proccesed['text'],bow_model=bowler_model)
df_generated


entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al if de df
entraste al i

raw_data  \
0                                               ¡Hola!   
1                                         Buenos días.   
2                                       Buenas tardes.   
3                                       Buenas noches.   
4                                            ¿Qué tal?   
..                                                 ...   
395              ¿Qué me sugieres ver en este momento?   
396             ¿Qué está bueno para ver en streaming?   
397   ¿Algún programa que me atrape desde el princi...   
398        ¿Qué serie o película me recomendarías hoy?   
399    ¿Algún título interesante para ver en pantalla?   

                                                tokens  \
0                                               [hola]   
1                                       [buenos, dias]   
2                                     [buenas, tardes]   
3                                     [buenas, noches]   
4                                           [que, tal]   
..                                                 ...   
395        [que, me, sugieres, ver, en, este, momento]   
396       [que, esta, bueno, para, ver, en, streaming]   
397  [algun, programa, que, me, atrape, desde, el, ...   
398  [que, serie, o, pelicula, me, recomendarias, hoy]   
399  [algun, titulo, interesante, para, ver, en, pa...   

                                        no stops words  \
0                                             [[hola]]   
1                                   [[buenos], [dias]]   
2                                 [[buenas], [tardes]]   
3                                 [[buenas], [noches]]   
4                                       [[que], [tal]]   
..                                                 ...   
395  [[que], [me], [sugieres], [ver], [en], [este],...   
396  [[que], [esta], [bueno], [para], [ver], [en], ...   
397  [[algun], [programa], [que], [me], [atrape], [...   
398  [[que], [serie], [o], [pelicula], [me], [recom...   
399  [[algun], [titulo], [interesante], [para], [ve...   

                              lematization  \
0                                    [hol]   
1                             [buen, dias]   
2                             [buen, tard]   
3                             [buen, noch]   
4                                    [tal]   
..                                     ...   
395                  [sugier, ver, moment]   
396                 [buen, ver, streaming]   
397      [algun, program, atrap, principi]   
398      [seri, pelicul, recomendari, hoy]   
399  [algun, titul, interes, ver, pantall]   

                                            text coded  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
395  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
396  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
397  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
398  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
399  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[400 rows x 5 columns]

In [78]:
x_data = df_generated['text coded'].values #elemnts of each array are already floats
y_data= np.asarray(df_proccesed['target'].values,dtype='float32')

In [79]:
x_data.shape, y_data.shape

((400,), (400,))

In [80]:
type(x_data), type(y_data)

(numpy.ndarray, numpy.ndarray)

In [124]:
x_data[220], y_data[220]

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 

In [82]:
from sklearn.model_selection import train_test_split #split data
x_train, x_test, y_train, y_test = train_test_split(x_data,y_data,test_size=0.2,random_state=42)

In [83]:
print('x train: {} x test: {} y train: {} y test: {}'.format(x_train.shape,x_test.shape,y_train.shape,y_test.shape)) 

x train: (320,) x test: (80,) y train: (320,) y test: (80,)


In [84]:
x_train.tolist()

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 

In [85]:
x_train.shape

(320,)

In [86]:
y_train.shape

(320,)

In [87]:
from sklearn.naive_bayes import MultinomialNB


In [88]:
model_clasificator = MultinomialNB()
model_clasificator.fit(x_train.tolist(),y_train)

MultinomialNB()

In [89]:
y_test,y_train

(array([3., 3., 1., 3., 1., 1., 4., 1., 3., 2., 1., 4., 1., 1., 2., 1., 3.,
        4., 3., 4., 1., 1., 4., 3., 1., 4., 2., 3., 3., 2., 4., 2., 3., 1.,
        3., 2., 2., 4., 2., 2., 4., 1., 1., 1., 1., 4., 2., 2., 1., 2., 1.,
        4., 4., 1., 4., 1., 3., 2., 1., 2., 2., 3., 3., 1., 2., 1., 4., 3.,
        4., 1., 4., 2., 1., 1., 4., 3., 3., 4., 2., 3.], dtype=float32),
 array([1., 1., 3., 3., 3., 1., 3., 4., 2., 1., 3., 4., 2., 3., 2., 4., 4.,
        4., 3., 1., 3., 2., 1., 1., 2., 1., 1., 2., 4., 4., 2., 4., 3., 4.,
        3., 1., 1., 3., 4., 3., 2., 2., 1., 4., 1., 2., 4., 4., 2., 3., 4.,
        2., 3., 2., 2., 2., 3., 3., 3., 4., 1., 2., 3., 2., 2., 3., 1., 2.,
        2., 4., 1., 4., 3., 2., 1., 2., 2., 1., 4., 4., 4., 3., 3., 2., 4.,
        1., 4., 2., 2., 3., 1., 1., 2., 1., 2., 4., 1., 3., 1., 1., 1., 2.,
        2., 2., 1., 2., 4., 3., 4., 2., 2., 2., 4., 1., 4., 4., 4., 4., 4.,
        4., 2., 3., 3., 3., 3., 2., 1., 1., 4., 2., 3., 2., 2., 4., 3., 2.,
        4., 3.,

In [90]:
y_predict = model_clasificator.predict(x_test.tolist())
y_predict

array([3., 2., 3., 3., 1., 1., 4., 1., 3., 1., 1., 4., 1., 1., 2., 1., 3.,
       4., 3., 4., 1., 3., 4., 3., 1., 4., 2., 3., 3., 2., 4., 2., 3., 1.,
       3., 2., 2., 4., 2., 2., 3., 1., 1., 1., 1., 4., 2., 2., 2., 2., 1.,
       4., 4., 1., 4., 1., 3., 2., 1., 2., 2., 3., 4., 1., 2., 1., 3., 3.,
       4., 1., 4., 2., 2., 1., 4., 3., 3., 4., 2., 3.], dtype=float32)

In [91]:
y_predict,y_test

(array([3., 2., 3., 3., 1., 1., 4., 1., 3., 1., 1., 4., 1., 1., 2., 1., 3.,
        4., 3., 4., 1., 3., 4., 3., 1., 4., 2., 3., 3., 2., 4., 2., 3., 1.,
        3., 2., 2., 4., 2., 2., 3., 1., 1., 1., 1., 4., 2., 2., 2., 2., 1.,
        4., 4., 1., 4., 1., 3., 2., 1., 2., 2., 3., 4., 1., 2., 1., 3., 3.,
        4., 1., 4., 2., 2., 1., 4., 3., 3., 4., 2., 3.], dtype=float32),
 array([3., 3., 1., 3., 1., 1., 4., 1., 3., 2., 1., 4., 1., 1., 2., 1., 3.,
        4., 3., 4., 1., 1., 4., 3., 1., 4., 2., 3., 3., 2., 4., 2., 3., 1.,
        3., 2., 2., 4., 2., 2., 4., 1., 1., 1., 1., 4., 2., 2., 1., 2., 1.,
        4., 4., 1., 4., 1., 3., 2., 1., 2., 2., 3., 3., 1., 2., 1., 4., 3.,
        4., 1., 4., 2., 1., 1., 4., 3., 3., 4., 2., 3.], dtype=float32))

In [92]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)
cm

array([[22,  2,  2,  0],
       [ 1, 17,  0,  0],
       [ 0,  1, 16,  1],
       [ 0,  0,  2, 16]])

In [93]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predict)

0.8875

In [94]:
from module_pro import generate_model, bow_text
bow_model =generate_model(df_proccesed['text'],df=True)

In [95]:
bow_text('hola',bow_model=bow_model,df=False)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [119]:
def get_prediction(bow_model,model_clasification):
    texto = input('you: ')
    if texto.lower() == 'salir':
        return False
    else:
        from module_pro import bow_text
        texto_codex = bow_text(texto,bow_model=bow_model,df=False)
        prediction = model_clasification.predict(texto_codex.reshape(1,-1))
        probabilities = model_clasification.predict_proba(texto_codex.reshape(1,-1))
        print('saludo, presentacion, infomacion, recomendacion')
        print(probabilities)
        if probabilities[0][0] >0.30:
            print('target: saludo')
        elif probabilities[0][1] >0.30:
            print('target: presentacion')
        elif probabilities[0][2] >0.30:
            print('target: informacion')
        elif probabilities[0][3] >0.30:
            print('target: recomendacion')
        else: 
            print('targget: no match')
        return True
        #print(prediction)

In [122]:
print('Para salir del chat solo escribe exit o salir')
c= True
while c == True:
    c = get_prediction(bow_model=bow_model,model_clasification=model_clasificator) == True


Para salir del chat solo escribe exit o salir
